// ---------------------------------------------------------------------------
//  /robots.txt — generated at build time from SITE.url (src/consts.ts).
//
//  Replaces the former static `public/robots.txt`, which hardcoded the
//  placeholder domain in its `Sitemap:` line and silently shipped the wrong
//  origin. Prerendered on purpose: no Worker invocation per crawl, and the
//  domain is resolved once at build from the same source as the sitemaps.
//
//  To change the production origin, set the PUBLIC_SITE_URL build variable —
//  do not edit this file.
// ---------------------------------------------------------------------------
import type { APIRoute } from "astro";
import { SITE } from "@/consts";

export const prerender = true;

export const GET: APIRoute = () => {
  // Rule set is intentionally identical to the retired public/robots.txt —
  // this change fixes ONLY the hardcoded origin.
  const body = `User-agent: *
Allow: /
Disallow: /admin/
Disallow: /admin-v2/

Sitemap: ${SITE.url}/sitemap-index.xml
`;

  return new Response(body, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
};
