-- V4.1: Daily AI-style operation recommendations
-- Generated by cron-pull after each data pull.
-- Dashboard reads the latest snapshot for actionable suggestions.

CREATE TABLE IF NOT EXISTS daily_recs (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  date        TEXT NOT NULL,          -- YYYY-MM-DD (generation date)
  category    TEXT NOT NULL,          -- opportunity | anomaly | hot_product | seo_tip | content_tip
  priority    TEXT NOT NULL DEFAULT 'medium', -- high | medium | low
  title       TEXT NOT NULL,
  detail      TEXT,
  metric_val  REAL DEFAULT 0,        -- numeric score for sorting
  created_at  INTEGER NOT NULL       -- unix timestamp
);

CREATE INDEX IF NOT EXISTS idx_daily_recs_date ON daily_recs(date);
CREATE INDEX IF NOT EXISTS idx_daily_recs_category ON daily_recs(category);
