-- 0024: Add short_id column to commerce_products for compact PDP URLs
-- short_id is a 10-char hex string generated by scripts/gen-short-ids.mjs
-- Column added, short_ids generated, and unique index created via the script.
-- This file is kept for documentation / replay purposes.

-- The actual steps performed:
-- 1. ALTER TABLE commerce_products ADD COLUMN short_id TEXT DEFAULT '';
-- 2. scripts/gen-short-ids.mjs generated unique 10-char hex short_ids for all 404 products
-- 3. CREATE UNIQUE INDEX idx_commerce_products_short_id ON commerce_products(short_id)

-- Verify:
-- SELECT COUNT(*) as total, COUNT(short_id) as with_id, COUNT(DISTINCT short_id) as unique_ids FROM commerce_products;
