// GET /api/admin/load — list content entries with summary frontmatter.
//
// V3 fix: previously fetched each .md file individually from GitHub (1 ghGet
// per file). With 82 products × 3 locales = 246 files, this exceeded
// Cloudflare's 50-subrequest-per-Worker limit and broke the admin in
// production. Now reads a single build-time manifest (/admin-manifest.json,
// generated by src/pages/admin-manifest.json.ts) — 1 subrequest total.
// KV drafts are overlaid on top (KV ops don't count as subrequests).
//
// Supports ?collection=blog|products|guides|caseStudies to load one collection
// (the client loads them separately for progressive rendering).

import type { Env } from "../../types";
import { listDrafts, getDraft, isAuthed, json } from "./shared";

type CollectionName = "blog" | "products" | "guides" | "caseStudies";

const ALL_COLLECTIONS: CollectionName[] = ["blog", "products", "guides", "caseStudies"];

interface ManifestEntry {
  key: string;
  locale: string;
  id: string;
  title: string;
  category: string;
  cover: string;
  pubDate?: string;
  moq?: string;
  origin?: string;
  leadTime?: string;
  country?: string;
  region?: string;
  order?: number;
  featured: boolean;
  draft: boolean;
}

// One row in the admin content list. Frontmatter fields are overlaid from KV
// drafts, so their value types vary — keep them `unknown` until the client
// renders them.
interface LoadEntry {
  key: string;
  locale: string;
  path: string;
  sha: string | null;
  hasDraft: boolean;
  [field: string]: unknown;
}

// Minimal frontmatter parser for KV draft overlays.
function parseFrontmatter(raw: string): Record<string, unknown> {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return {};
  const out: Record<string, unknown> = {};
  for (const line of m[1].split(/\r?\n/)) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const k = line.slice(0, idx).trim();
    if (!k) continue;
    let v: unknown = line.slice(idx + 1).trim();
    if (
      typeof v === "string" &&
      v.length >= 2 &&
      ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'")))
    ) {
      const inner = v.slice(1, -1);
      try {
        v = v.startsWith('"') ? JSON.parse(v) : inner;
      } catch {
        v = inner;
      }
    } else if (v === "true") v = true;
    else if (v === "false") v = false;
    out[k] = v;
  }
  return out;
}

const SUMMARY_FIELDS = [
  "title",
  "excerpt",
  "category",
  "cover",
  "pubDate",
  "moq",
  "origin",
  "leadTime",
  "country",
  "region",
  "order",
  "featured",
  "draft",
];

function summarize(raw: string | null): Record<string, unknown> {
  if (!raw) return {};
  const fm = parseFrontmatter(raw);
  const s: Record<string, unknown> = {};
  for (const f of SUMMARY_FIELDS) {
    if (fm[f] !== undefined) s[f] = fm[f];
  }
  return s;
}

export const onRequestGet: PagesFunction<Env> = async ({ request, env }) => {
  if (!(await isAuthed(request, env))) return json({ error: "Unauthorized" }, 401);

  try {
    const only = new URL(request.url).searchParams.get("collection");

    // Fetch the build-time manifest (1 subrequest to same origin).
    const manifestUrl = new URL("/admin-manifest.json", request.url);
    const res = await fetch(manifestUrl.toString());
    if (!res.ok) {
      return json(
        {
          error:
            "Failed to load content manifest. The site may be rebuilding — try again in a minute.",
        },
        502,
      );
    }
    const manifest: Record<CollectionName, ManifestEntry[]> = await res.json();

    const out: Record<CollectionName, LoadEntry[]> = {
      blog: [],
      products: [],
      guides: [],
      caseStudies: [],
    };
    const collections: CollectionName[] =
      only && ALL_COLLECTIONS.includes(only as CollectionName)
        ? [only as CollectionName]
        : ALL_COLLECTIONS;

    for (const c of collections) {
      const entries = manifest[c] || [];
      out[c] = entries.map((e) => ({
        key: e.key,
        locale: e.locale,
        path: `src/content/${c}/${e.key}.${e.locale}.md`,
        sha: null, // fetched fresh when opening the editor
        title: e.title,
        category: e.category,
        cover: e.cover,
        pubDate: e.pubDate || "",
        moq: e.moq || "",
        origin: e.origin || "",
        leadTime: e.leadTime || "",
        country: e.country || "",
        region: e.region || "",
        order: e.order || 0,
        featured: e.featured,
        draft: e.draft,
        hasDraft: false,
      }));
    }

    // Overlay KV drafts (KV operations don't count toward subrequest limit).
    const drafts = await listDrafts(env);
    for (const dk of drafts) {
      const m = dk.match(/^draft:(blog|products|guides|caseStudies):(.+):(en|es|de)$/);
      if (!m) continue;
      const [, c, key, locale] = m as [string, CollectionName, string, string];
      if (only && c !== only) continue;
      const draftRaw = await getDraft(env, c, key, locale);
      const summary = summarize(draftRaw);
      const existing = out[c].find((x) => x.key === key && x.locale === locale);
      if (existing) {
        existing.hasDraft = true;
        Object.assign(existing, summary);
      } else {
        out[c].push({
          key,
          locale,
          path: `src/content/${c}/${key}.${locale}.md`,
          sha: null,
          hasDraft: true,
          ...summary,
        });
      }
    }

    return json(out);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return json({ error: `Load failed: ${msg}` }, 500);
  }
};
